name: meshcompression
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0=hcec6c5f_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - cairo=1.16.0=h08824b9_6
  - dav1d=1.2.1=h6c40b1e_0
  - expat=2.7.1=h6d0c2b6_0
  - ffmpeg=6.1.1=hd2ef4e1_3
  - fontconfig=2.14.1=h269ac6a_3
  - freetype=2.13.3=h02243ff_0
  - fribidi=1.0.10=haf1e3a3_0
  - gdk-pixbuf=2.42.10=h688160f_2
  - gettext=0.21.0=h4e8c18a_2
  - giflib=5.2.2=h46256e1_0
  - glib=2.84.2=h918fcf5_0
  - glib-tools=2.84.2=h918fcf5_0
  - graphite2=1.3.14=he9d5cce_1
  - harfbuzz=10.2.0=h060d35a_1
  - icu=73.1=hcec6c5f_0
  - jpeg=9e=h46256e1_3
  - lame=3.100=h1de35cc_0
  - leptonica=1.82.0=h7d8ae9a_3
  - lerc=4.0.0=h6d0c2b6_0
  - libarchive=3.7.7=h4c66a04_0
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h46256e1_0
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libglib=2.84.2=heb90364_0
  - libiconv=1.16=h6c40b1e_3
  - libmpdec=4.0.0=h46256e1_0
  - libogg=1.3.5=hca72f7f_1
  - libopenblas=0.3.29=h3f8574a_0
  - libopus=1.3.1=h46256e1_1
  - libpng=1.6.39=h6c40b1e_0
  - librsvg=2.56.3=h3d4ac1e_2
  - libtheora=1.1.1=hca72f7f_3
  - libtiff=4.7.0=h2dfa3ea_0
  - libvorbis=1.3.7=haf1e3a3_0
  - libvpx=1.13.1=hcec6c5f_0
  - libwebp=1.3.2=hc927772_1
  - libwebp-base=1.3.2=h46256e1_1
  - libxml2=2.13.8=h6070cd6_0
  - llvm-openmp=19.1.7=h5048363_2
  - lz4-c=1.9.4=hcec6c5f_1
  - ncurses=6.5=h923df54_0
  - numpy=2.3.1=py313h1a2ec72_0
  - numpy-base=2.3.1=py313hce0bb57_0
  - openh264=2.1.1=h8346a28_0
  - openjpeg=2.5.2=h2d09ccc_1
  - openssl=3.0.17=hee2dfae_0
  - pango=1.50.7=h02415e8_2
  - pcre2=10.42=h9b97e30_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=hb254d66_0
  - python=3.13.5=h81a7116_100_cp313
  - python_abi=3.13=0_cp313
  - readline=8.3=h49f2429_0
  - setuptools=72.1.0=py313hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - tesseract=5.2.0=h6d0c2b6_2
  - tk=8.6.15=h3a5a201_0
  - trimesh=4.8.3=pyh7b2049a_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py313hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
  - pip:
      - networkx==3.5
      - pyglet==1.5.31
      - scipy==1.16.3
prefix: /usr/local/Caskroom/miniconda/base/envs/meshcompression
