name: meshcompression
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0
  - blas=1.0=openblas
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - cairo=1.16.0
  - dav1d=1.2.1
  - expat=2.7.1
  - ffmpeg=6.1.1
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - giflib=5.2.2
  - glib=2.84.2
  - glib-tools=2.84.2
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - jpeg=9e
  - lame=3.100
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.7.7
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.84.2
  - libiconv=1.16
  - libmpdec=4.0.0
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopus=1.3.1
  - libpng=1.6.39
  - librsvg=2.56.3
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - llvm-openmp=19.1.7
  - lz4-c=1.9.4
  - numpy=2.3.1
  - numpy-base=2.3.1
  - openjpeg=2.5.2
  - openssl=3.0.17
  - pango=1.50.7
  - pcre2=10.42
  - pip=25.2
  - pixman=0.46.4
  - python=3.13.5
  - python_abi=3.13
  - setuptools=72.1.0
  - sqlite=3.50.2
  - tesseract=5.2.0
  - tk=8.6.15
  - trimesh=4.8.3
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - networkx==3.5
      - pyglet==1.5.31
      - scipy==1.16.3
  - dracopy
  - pandas
  - tqdm
prefix: /usr/local/Caskroom/miniconda/base/envs/meshcompression
